# Generated by Django 4.2.7 on 2023-11-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
