# Generated by Django 4.2.7 on 2023-11-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_picture_contact_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, default='pictures/fotopadrao.jepg', upload_to='pictures/%Y%m'),
        ),
    ]
